### ISSUE TITLE
Refactor AuthorizationHelper to enable dependency injection

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-storage#1]
## Description
The AuthorizationHelper class in Storage is currently being instantiated by a few controllers and other classes that needs help in authorization. We should extract operations that depend on IPDP to a separate class that can be added to the DI container.

Let AuthorizationHelper keep the static helper operations for now.

## Considerations
- Take special care to evaluate the instantiation Scope for the new class. Start with "AddTransitional" if unsure.
- This change will trigger significant work related to unit tests. Unless we allow unit tests to use a real instance of the new service as opposed to a mock.

## Acceptance criteria
No class use the `new` keyword to obtain an AuthorizationHelper.

## Development tasks
- [x] Create a interface describing the non-static operations in AuthorizationHelper.
- [x] Implement a service class using the service contract.
- [x] Add service to DI.
- [x] Update all classes currently using `new` to obtain an AuthorizationHelper to instead get this through their constructor.
- [x] Maintain unit tests for storage. Consider using a mock or a real service instance in each case. There is already a mock for IPDP with a large test data set behind.
- [x] QA
- [x] Manual test is complete (if relevant)
- [x] Automated test is implemented (if relevant)

**Comment by vgr** [comment]
Gjennomført manuell test av endringene mot AT22.
Testet OK!
