### ISSUE TITLE
Performance issue with the process.isComplete parameter

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-storage#10]
## Description
The Storage endpoint GetInstances has a parameter called process.isComplete that adds a where clause that involves a null check. Null checking in CosmosDB has poor performance. See [#5284](https://github.com/Altinn/altinn-studio/issues/5284).

The ProcessState class will need a new property called IsComplete or similar that should be used instead of the current `Ended != null` check. If possible the property should be read only. The value should be based on the whether the Ended property is set or not. The goal of keeping it read only would be to avoid needing to keep it updated in sync with the Ended property of the Process. The important part here is that the serialized version of Instance is stored in CosmosDB with a property called IsComplete so that it can be used in queries.

One major challenge is to update all existing Instances with the the new property. A possible solution is to support both the new and old way of querying CosmosDB with an OR.

## Considerations
Try to make the new property "read only". The property must be included during serialization and deserialization must bee able to ignore it.

## Acceptance criteria
All new instances with a started process must have the Process.IsComplete property.
- If Ended == null, then IsComplete is false
- If Ended != null then IsComplete is true

## Development tasks
- [ ] Add a new "readonly" Property IsComplete to ProcessState
- [ ] Update the query created by InstanceRepository. (Maybe also support existing method in an OR?)
- [ ] Update all existing instances with the new property.
    - [ ] Create a program to patch all instances.
    - [ ] Consider deleting some instances is possible.
    - [ ] Run the patch program in all environments.
- [ ] Add an isComplete query to a test script
- [ ] Document and anounce the addition of the new property in case there are external systems that are unable to handle unknown properties.

## Test
- [ ] Run som isComplete queries.

## Definition of done
Verify that this issue meets [DoD](https://confluence.brreg.no/display/T3KP/Definition+of+Done#DefinitionofDone-DoD%E2%80%93utvikling) (Only for project members) before closing.

- [ ] Documentation is updated (if relevant)
  - [ ] Technical documentation (docs.altinn.studio)
  - [ ] User documentation (altinn.github.io/docs)
- [ ] QA
- [ ] Manual test is complete (if relevant)
- [ ] Automated test is implemented (if relevant)
- [ ] All tasks in this userstory are closed (i.e. remaining tasks are moved to other user stories or marked obsolete)

**Comment by acn-sbuad** [comment]
Obsolete. parameter does not cause a performance issue with postgres as the db
