### ISSUE TITLE
Establish routines for restore of data from Storage to CosmosDB using Cosmos DB Migration Toolkit and test these

### ISSUE THREAD

**Issue by knuthalvor** [Altinn/altinn-storage#106]
## Description
Based on post mortem, establish better routines for restore of data from backup storage to CosmosDB using the Cosmos DB Migration Toolkit

## Considerations
See also USER STORY 50965.

## Acceptance criteria
Routines are written and tested.

## Definition of done
Verify that this issue meets [DoD](https://confluence.brreg.no/display/T3KP/Definition+of+Done#DefinitionofDone-DoD%E2%80%93utvikling) (Only for project members) before closing.

- [ ] Documentation is updated (if relevant)
- [ ] QA
- [ ] Manual test is complete (if relevant)
- [ ] All tasks in this userstory are closed (i.e. remaining tasks are moved to other user stories or marked obsolete)

**Comment by SandGrainOne** [comment]
Cosmos DB now have better support for continuous backup (see issue: https://github.com/Altinn/altinn-platform/issues/293) Work on disaster recovery and data restore continues in other issues.
