### ISSUE TITLE
Controllers in Storage are using the CosmosDB library

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-storage#11]
## Description
Many of the controllers in Storage are currently using classes from the CosmosDB library. This is breaking isolation between data layer and business related logic. The Controllers and Repositories must be refactored so that any usage og the CosmosDB library can be removed from the controllers.

This should make it easier to perform a replacement of CosmosDB later if that becomes necessary. 

- Have as little exception handling as possible. Exceptions that are unrecoverable should pass through. Exceptions that can be handled should be caught as early as possible. "NotFound" is one such example. 
- If there are CosmosDB related Exceptions that must be handled by the controller, they must first be handled by Repository and changed into an exception known to the controller logic. (Dependency Inversion)

## Acceptance criteria
There are no use of any CosmosDB classes outside of the Repository classes and data access layer related logic.

## Development tasks
- [ ] Remove all using of CosmosDB related classes in Controllers and other classes related to business logic and presentation.
- [ ] Update LocalTest with updated Storage Controllers and remove LocalTest dependency on the CosmosDB library.

## Test
- [ ] Regression test. No new functionality.

## Definition of done
Verify that this issue meets [DoD](https://confluence.brreg.no/display/T3KP/Definition+of+Done#DefinitionofDone-DoD%E2%80%93utvikling) (Only for project members) before closing.

- [ ] Documentation is updated (if relevant)
  - [ ] Technical documentation (docs.altinn.studio)
  - [ ] User documentation (altinn.github.io/docs)
- [ ] QA
- [ ] Manual test is complete (if relevant)
- [ ] Automated test is implemented (if relevant)
- [ ] All tasks in this userstory are closed (i.e. remaining tasks are moved to other user stories or marked obsolete)

**Comment by acn-sbuad** [comment]
Dependency removed when cosmos SDK was replaced
