### ISSUE TITLE
Optimize Cosmos DB index configuration

### ISSUE THREAD

**Issue by b-brodie-digdir** [Altinn/altinn-storage#111]
### Description

Based on documented efforts by other Cosmos DB users, there can be a significant reduction in RUs (Cosmos DB cost units) if only necessary attributes are included in indexes. Preferably, a baseline should be established and sufficiently documented before making changes that affect performance.

### In-scope

Define new index configurations based on include lists for known attributes. 
Ensure that there are no negative impacts to performance or changes in functionality.

Collections:
Instances: No changes for now.
InstanceEvents: We have no search in this collection. Get on ID or PartitionKey only.
DataElements: We have no search in this collection from user interaction. The cleanup job might have logic related to "AppLogic.AutoDeleteOnProcessEnd". This means we would need to keep an index on the IsHardDeleted attribute.

Consider removing all default indexes for the InstanceEvents and DataElements collections.

### Heuristic rules for how to optimize index policy

1. Start with ExcludePaths for known attributes that are not used in any queries, focusing on attributes that can contain subtrees.
- Examples: Instance.Data
2. Switch to IncludePaths when analysis of read patterns is complete, to avoid indexing new attributes added over time.
3. Use the Cosmos DB profiler to detect index utilization on queries.

NOTE: attributes used in sort operations MUST be indexed. If multiple columns are used in a sort expression, consider defining a Composite Index to avoid table scan overhead.

### Out of scope

Changing the shape of existing documents, search implementation, etc.

### Acceptance criteria
- [x] Write down a way for us to determine a good index policy.

**Comment by acn-sbuad** [comment]
Regression test of messagebox and Storage API as end user successful. Use case tests running green. Closing issue
