### ISSUE TITLE
Implement best practices for Cosmos DB configuration

### ISSUE THREAD

**Issue by b-brodie-digdir** [Altinn/altinn-storage#113]
### Description

Microsoft has provided updated guidance for best practice use of Cosmos DB. 

We should analyze our current implementation and compile a list of adjustments required in order to align with this guidance where applicable.

References:
https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/best-practice-dotnet

https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/performance-tips-dotnet-sdk-v3?tabs=trace-net-core

### In scope

Evaluate changing connection mode to Direct or increasing the MaxConnectionLimit.

In .NET SDK 1.8.0 and later, the default value for ServicePointManager.DefaultConnectionLimit is 50. To change the value, you can set Documents.Client.ConnectionPolicy.MaxConnectionLimit to a higher value.
(https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/best-practice-dotnet#best-practices-when-using-gateway-mode)

### Analysis

Evaluated:

1. EnableContentResponseOnWrite = false

Results: no impact on RU, minimal impact for most instances due to small document size.

2. Co-locate multiple entity types
https://learn.microsoft.com/en-us/azure/cosmos-db/optimize-cost-reads-writes

This has not been tested as it would require a non-trivial refactor. Main benefits include support for ACID transactions, as well as a reduction in RU required for all CRUD operations.

3. Singleton Client

This is implemented in #111 (PR #120). Performance improvements are not expected as all a defacto singleton instance has been in effect via singleton containers containing the only Cosmos client reference. This change does open up for easier profiling and was a requirement for setting index policy per container.

4. Connectivity mode

It is recommended to use Direct connection mode. We currently use Gateway mode, which introduces an extra SSL termination. During load testing it was not possible to determine any noticeable speed or scaling difference, but real world conditions may indicate otherwise. One suggestion would be to expose this setting as an environment variable and perform some comparisons in production.

### Best practices when using Gateway mode
Increase System.Net MaxConnections per host when you use Gateway mode. Azure Cosmos DB requests are made over HTTPS/REST when you use Gateway mode. They're subject to the default connection limit per hostname or IP address. You might need to set MaxConnections to a higher value (from 100 through 1,000) so that the client library can use multiple simultaneous connections to Azure Cosmos DB. In .NET SDK 1.8.0 and later, the default value for ServicePointManager.DefaultConnectionLimit is 50. To change the value, you can set Documents.Client.ConnectionPolicy.MaxConnectionLimit to a higher value.

NOTE: client configuration setting has been renamed to `GatewayModeMaxConnectionLimit`

This is currently a part of #111 

Source:
https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/best-practice-dotnet#best-practices-when-using-gateway-mode

**Comment by acn-sbuad** [comment]
Closing issue as suggestions have been implemented in storage
