### ISSUE TITLE
Create Instance and InstanceEvent in Transaction batch

### ISSUE THREAD

**Issue by bdb-dd** [Altinn/altinn-storage#118]
### Description

Reduce possibility for discrepancies between Instance and InstanceEvent collections by wrapping both operations in a single Transaction batch. This will require some refactoring of the respective repositories.

### Additional Information

[Transactional batch api](https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/transactional-batch?tabs=dotnet)

**Comment by SandGrainOne** [comment]
Consistency between these two instanec are not critical enough to take the cost of a transaction.
