### ISSUE TITLE
Extend free text search to find matches on instance

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-storage#123]
## Description
Instance exposes both presentation fields and data values.
These fields should be searchable from the search API.

## Considerations
- [x] Do we require a minimum number of characters before doing a search? 
  - No such requirement in A2. Following same behavior
- [ ] How do we optimize the process of searching for a match in  presentation fields and/or data values?  
- [x] Should a feature switch be included so adequate performance tesiting can be conducted before the functionality is deployed to production? 
  - No.

## Acceptance criteria
- [ ] Performance of the search API cannot be significantly decreased due to this change.
- [x] Using free text search in the messagebox is able to find matches based on presentation field. 
- [ ] Using free text search in the messagebox is able to find matches based on data values 
- [ ] If the text matches either presentation field, data values or title it should be returned as a match

## Specification taks
- [ ] Define the order of search in order to optimize performance w.r.t. searching both app titles and 

## Development tasks
- [ ] Set a bench mark for the free text search before implementation
- [x] Implement logic for finding a match on presentation field when using the search endpoint
- [ ] Implement logic for finding a match on data values when using the search endpoint
- [ ] Compare performance of free text search after implementation
- [ ] QA
- [ ] Manual test is complete

## Test
> Add test cases here as checkboxes that are being tested as part of the changes.

**Comment by FTLems** [comment]
Can we get org/krt tag on this issue?

**Comment by acn-sbuad** [comment]
Bug or irregularity related to the date filters. Tested in AT22, testuser 12928296855

Search word: 1234
Altering between period 2022 and all periods. An addition element is sorted under 2022 for all periods, but does not show up in the specific period search

https://github.com/Altinn/altinn-storage/assets/47737608/e6b981a9-9670-40d9-a011-efa54bc09f77

**Comment by acn-sbuad** [comment]
Characters with accents are not supported by the search. E.g. è. à etc.

Given the presentation field: `André-test`
Messagebox does not allow you to search for `André` (`Andr` is allowed), and `Andre will yield an empty result. `

**Comment by acn-sbuad** [comment]
Regression test of `Bug or irregularity related to the date filters`  successful in AT22

**Comment by acn-sbuad** [comment]
`Characters with accents are not supported by the search. E.g. è. à etc.` won't be fixed as behavior matches Altinn 2.

**Comment by acn-sbuad** [comment]
Search on presentation texts fully implemented. Moving back to backlog as data values are not covered yet. PO can consider whether this is still a requirement or not.

**Comment by olebhansen** [comment]
Closing. Will follow up "advanced search" in a roadmap.
