### ISSUE TITLE
Misspelled word

### ISSUE THREAD

**Issue by DanRJ** [Altinn/altinn-storage#147]
### Description of the bug

This is a tiny bug regarding this Enum:
https://github.com/Altinn/altinn-storage/blob/main/src/Storage.Interface/Enums/InstanceEventType.cs

The enum property "Submited" is spelled wrong. It's correctly spelled "Submitted".
This is not a blocker for anyone, however when searching for instance events using the InstanceEvents API, the query parameter eventTypes allows searching for types, where the enum value is a string. 

Updating this spelling error in a patch or minor version will potentially start returning nothing for existing users.

I suggest fixing this issue when altinn-storage is deploying a new major release.

### Steps To Reproduce

*

**Comment by SandGrainOne** [comment]
Unfortunatly too much work for too little gain
