### ISSUE TITLE
Søk på dagens dato viser ikke app innsendt i dag

### ISSUE THREAD

**Issue by elenagustafsson** [Altinn/altinn-storage#199]
### Description of the bug

Søk i Altinn (TT2) viser ikke Altinn 3 app innsendt i dag: har akkurat sendt inn RF-1551, jeg har for mange elementer i arkivet og velger avansert søk på dagens dato, men RF-1551 vises ikke. Velger jeg søk "siste måned" så vises innsendte appen. Se vedlagte skjermdumper.
![image](https://github.com/Altinn/altinn-storage/assets/80962333/4b73caac-19ad-4cf6-bff2-58a237fd6f11)
![image](https://github.com/Altinn/altinn-storage/assets/80962333/ed4d3701-a236-4b93-8913-bf1ca2d3704a)

### Steps To Reproduce

1. Send inn app
2. Gå inn i avansert søk og velg Periode - Velg periode står som default på dagens dato
3. Det vises ikke appen sendt inn i dag

**Comment by aas-tbuar** [comment]
@elenagustafsson Kan du forsøke å endre søket ditt til 10.5.2023- 12.5-2023. Sjekk om det gjør at visningen endres.

**Comment by elenagustafsson** [comment]
Søket fungerer i dag. Har prøvd flere forskjellige måter, og det funker. Usikker hva som var årsaken til oppførselen av søket dagen før.

**Comment by aas-tbuar** [comment]
Lukkes da de ikke kunne reprodusere feil.
