### ISSUE TITLE
Limiting the access details for the SAS-Definition used against blob storage.

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-storage#21]
There are (probably) room for improvements in what kind of permissions Storage is granted through the generated SAS-key when accessing application owner blob storage. This issue should identify the minimum of required access and make necessary changes to the terraform script.

https://docs.microsoft.com/en-us/rest/api/storageservices/versioning-for-the-azure-storage-services

- Which signed_version?
   - Needs to match the type of access we need. It looks like blob storage is supported by the oldest versions.
- Which resource types?
   - object only?
- Which services?
   - Blob only?
- Which permissions?
   - read, write, delete, list, add, create?
   - update and process not needed?

**Comment by annerisbakk** [comment]
@SandGrainOne Aktuell for refinement?

**Comment by SandGrainOne** [comment]
@annerisbakk Not any time soon.

**Comment by SandGrainOne** [comment]
We'll be switching to managed identity instead.
