### ISSUE TITLE
DevOps 59697

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-storage#22]
See https://dev.azure.com/digdir/Altinn/_workitems/edit/59697

**Comment by SandGrainOne** [comment]
Trenger avklaringer fra IM

**Comment by SandGrainOne** [comment]
Unødvendig å avklare med IM. Vi skaffer oss oversikt over omfang og vurderer selv om vi bør utføre opprydding.

**Comment by OddArneSaetervik** [comment]
@Braskbram informerer skatt om problemstillingen og tiltaket, før vi foretar sanering.
