### ISSUE TITLE
Replace outdated SKD in functions

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-storage#25]
## Description
Platform Storage Functions  is currently using SKD Microsoft.Azure.DocumentDB.Core for interaction with CosmosDB. 
A newer project is available [Microsoft.Azure.Cosmos](https://github.com/Azure/azure-cosmos-dotnet-v3). We should replace all use of the old SDK with this.

https://docs.microsoft.com/en-us/azure/cosmos-db/sql/sql-api-sdk-dotnet-standard

## Acceptance criteria
- [x] Microsoft.Azure.DocumentDB.Core  dependency is removed
- [x] All regression tests successful

## Development tasks

- [x] Update SDK and fix all implementation w.r.t. integration with cosmos
- [x] QA
- [x] Manual test is complete (if relevant)

**Comment by tba76** [comment]
Merged 22/7. @acn-sbuad

**Comment by acn-sbuad** [comment]
Backup verified ok
