### ISSUE TITLE
Complete Storage changes and perform migration from CosmosDB to PostgreSQL

### ISSUE THREAD

**Issue by HenningNormann** [Altinn/altinn-storage#280]
```[tasklist]
### Pull requests
- [x] Review and merge "Standard code": https://github.com/Altinn/altinn-storage/pull/285
- [x] Review and merge "Cleanup triggers": https://dev.azure.com/brreg/altinn-studio-ops/_git/altinn-studio-ops/pullrequest/729
- [x] Review and merge: https://dev.azure.com/brreg/altinn-studio-ops/_git/altinn-studio-ops/pullrequest/788
```

```[tasklist]
### Infrastructure tasks
- [ ] https://github.com/Altinn/altinn-storage/issues/290
```

```[tasklist]
### Pre deploy activities
- [ ] https://github.com/Altinn/altinn-storage/issues/293
- [ ] https://github.com/Altinn/altinn-storage/issues/292
- [ ] https://github.com/Altinn/altinn-storage/issues/294
- [x] Walkthrough of the migration procedure
- [x] Set a date for migration in TT02 and write a downtime alert
- [x] Set a date for migration in Production and write a downtime alert.
- [x] Create a new release with UsePostgreSQL = true
```

### Perform migration

- Data migration - CosmosToPostgreSQL.exe in repo altinntools
    - Truncate tables if migration has been run in the environment in an earlier stage
    - Run full data migration (manually by Henning)
    - Run delta migrations until ready for go-live (manually by Henning)
- Stop write access to storage - update policy in APIM
- Run the final delta migration
- Stop running Cosmos data cleanup - e.g. stop the function in the azure portal
- Deploy code
- Re-enable write access to storage (ref. previous point)
- Remove downtime message

```[tasklist]
### Environments
- [x] AT21
- [x] AT22
- [x] AT23
- [x] AT24
- [x] YT01
- [x] TT02
- [x] Prod
```

```[tasklist]
### Regression test
- [x] Log in as the same users ad before conversion and compare
- [x] Follow up on Storage status
- [x] Investigate how Team Apps performs regression testing.
```

- Testing done so far:
  - Unit tests
  - Integration test including dB
  - Performance tests
  - A special version of storage that uses both the cosmos and postgres apis and compares the results has been run in yt01 and at22
  - Manual tests
    - Create list of areas to cover
      - By team
      - By ABS
   

```[tasklist]
### Cleanup
- [ ] https://github.com/Altinn/altinn-storage/issues/308
```

**Comment by SandGrainOne** [comment]
All issues have been closed. There are still a bit of cleanup to be done, but that is handled in other issues. (I hope)
