### ISSUE TITLE
Storage should have the option of searching for instances based on person or org number, or other

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-storage#3]
## What needs to be solved?
The current version of GetInstances in Storage can take a partyId in order to filter instances based on owner. This isn't really usable for external systems. Storage must be able to find partyid based on organization number, person number or username.

The assumption has been that application owners would search for instances on their app and not a specific instance owner, but this doesn't hold true in all cases. 

End user systems have a natural need to filter instances for a specific owner. Here we have a workaround using the party list endpoint on an app. Information given by that endpoint can be used to identify the partyId for a party they can represent.

## How do you want it solved?
A new input parameter hidden as a request header to hold the value. It should not be added as a query parameter as we don't want person number to appear in a url.

Header name suggestion: X-Ai-InstanceOwnerIdentifier

Value should have a prefix to indicate type of party:
- Person:&lt;Person number&gt;
- Organisation:&lt;Organisation number&gt;
- Username:&lt;Username&gt;

## Alternative solutions
A completely new endpoint accepting POST requests where the search parameters can be in the request body.

## Additional context

This issue might be affected by other issues related to GetInstances and how those are being implemented. E.g: #27 

## Development tasks

- [x] Add a parameter bound to a request header (see description)
- [x] Add logic to convert InstanceOwnerIdentifier to a party id.
- [x] Add unit tests
- [x] Update documentation
- [ ] Update API Management

## Acceptance criteria

- [x] The service can find instances based on a person number.
- [x] The service can find instances based on a organisation number.
- [ ] The service can find instances based on a username.

**Comment by SandGrainOne** [comment]
In the original issue @altinnadmin had the following comments:
>> End user systems have a natural need to filter instances for a specific owner
>
> Remember to consider performance and query cost if we implement something like this.
> Also consider if queries on Events can cover this need instead.
>
>> Person number as input parameter to the search must be transferred as a header value.
>
> If we need to expose this as a param, we should do it in a holistic way across all our APIs.
> Ref. for example  https://docs.altinn.studio/teknologi/altinnstudio/altinn-api/app-api/instances/#create-instance

The person lookup endpoint in register has a similar parameter called `X-Ai-NationalIdentityNumber`. The difference being that the person lookup endpoint is limited to persons, while here we want the parameter to support mulltiple instance owner types; person, organization and self identified (as a start).

Create instance is a POST making it more naturally to have all input in the body the request. With that being said I agree that we should try to standarize this across all endpoints.

Performing the party lookup will impact performance, not doubt. Our goal is to have external parties be notified about changes to instances through the event system. That puts less pressure on the query API, which in turn might allow us to adapt it for convenience above performance.

**Comment by acn-sbuad** [comment]
Testing in AT22. 

✅ Person header `X-Ai-InstanceOwnerIdentifier` Person:30838897408: Returns both active and archived instances for given person number.
✅ Matching person header and instanceOwner.PartyId `X-Ai-InstanceOwnerIdentifier` Person:30838897408 + `?instanceOwner.partyId=50155658`  Returns both active and archived instances for given person number.

❌ Mismatch person header and instanceOwner.PartyId returns instances for instanceOwner.partyId. Should return bad request. User can not provide both values

**Comment by acn-sbuad** [comment]
Tested OK in AT22
