### ISSUE TITLE
Active instances of decommissioned apps should be filtered out by Storage

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-storage#30]
## Description
Storage endpoints that returns instances must check the metadata of the associated app and ensure that the app is active. Instances based on an App that is "deactivated" should be removed from requested list. If such an instance is requested by id, the endpoint should return 404.

## Considerations
- [ ] If the elements are filtered out, an end user is never able to permanently delete the element. Given a larger app with the possibility to store large attachments, this means we are paying for permanent storage of data that will never be retrieved by either app owner or end user. 
- [x] How could Storage know that an app is decommissioned? Separate field in app metadata Cosmos

## Acceptance criteria
- [ ] GET `storage/api/v1/sbl/instances/search` does not return instances based on inactive apps.
- [ ] GET `storage/api/v1/sbl/instances/{instanceOwnerPartyId}/{instanceGuid}` returns NotFound if the app is inactive.
- [ ] GET `storage/api/v1/sbl/instances/{instanceOwnerPartyId}/{instanceGuid}/events` returns NotFound if the app is inactive.
- [ ] PUT `storage/api/v1/sbl/instances/{instanceOwnerPartyId}/{instanceGuid}/undelete` returns NotFound if the app is inactive.
- [ ] DELETE `storage/api/v1/sbl/instances/{instanceOwnerPartyId}/{instanceGuid}` returns NotFound if the app is inactive.

## Specification tasks
- [x] Development tasks are defined

## Development tasks
- [ ] Update Storage to support the acceptance criteria.
- [ ] Add field to app metadata
- [ ] QA
- [ ] Manual test is complete (if relevant)
- [ ] Automated test is implemented (if relevant)

**Comment by acn-sbuad** [comment]
How do we define a decomissioned app here? If an app owner decides to decommision an app we should have them consider what happens to existing instances and rather consiously hard delete them instead of masking the data. If they for some reason do not want to delete existing instances, that might be an argument for not decommisioning the application, but simply limiting the possibility to create new instances of it.

**Comment by nkylstad** [comment]
@acn-sbuad I agree, there should be a difference between decommissioning (complete removal of an app from environment) and simply disabling instantiation and/or submission of data.
By masking the data, the app owners can simply ignore the data. If it is truly no longer relevant the instances should be deleted, and this is something an app owner should have an active role in doing.

If we do go this route (i.e. doing nothing with existing instances and leaving it up to the app owners) - Is there some way we could update/append the data we pass to the inbox (f.ex. title or status) to indicate that the app is deprecated/unavailable? To make it a little less jarring for an end user who tries to access an instance of an app that no longer exists.

**Comment by SandGrainOne** [comment]
Closing in anticipation of a new and better plan for how the full process of a decommising of an app should work.
