### ISSUE TITLE
Change PostgreSQL server parameter

### ISSUE THREAD

**Issue by HenningNormann** [Altinn/altinn-storage#332]
The server parameter track_functions should be set to "all" for all Postgres servers.

**Comment by ootneim** [comment]
The parameter is set in  tag: "1.7.19"

**Comment by HenningNormann** [comment]
Når blir dette rullet ut?

**Comment by ootneim** [comment]
Ruller ut i at og yt i dag

**Comment by ootneim** [comment]
Deployed to all environments
