### ISSUE TITLE
Clean up in environment variable values defined through the helm chart after the removal of CosmosDB

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-storage#346]
### Description

There are a few settings that are no longer in use. The individual settings needs to be identified and removed. Any and all unused settings should be removed. Not only those associated with CosmosDB.

### Tasks

- [x] Clean up in values and remove unused settings

### Acceptance Criterias

- [x] Unnecessary environment variables are no longer defined for the Storage POD in k8

**Comment by acn-sbuad** [comment]
Moving to pri2 as it is a quick win.

**Comment by acn-sbuad** [comment]
No cosmos variables left in helm chart. Closing issue.
