### ISSUE TITLE
Application POST will reset created date and created by for existing apps

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-storage#361]
### Description of the bug

The POST endpoint for adding a new app either inserts a new app or updates existing ones by performing a simple conflict check in the SQL statement. However, this SQL statement overwrites both the created date and created by fields for existing apps. This SQL statement must be updated to prevent overwriting these created date and created by fields for existing apps. We also need to update the SQL statement used to update existing apps.

### Steps To Reproduce

1. Deploy the same application twice.
2. Notice that the created date is the timestamp of the last deploy. The same as the timestamp for last changed

**Comment by SandGrainOne** [comment]
@nkylstad We're wondering if altinn.studio should be responsible for setting the created date time of an application. Currently we're setting the date in the Post endpoint logic. We can remove that and respect the input from altinn-studio instead.

**Comment by nkylstad** [comment]
@SandGrainOne Studio sets `created` in applicationMetdata when creating an application. So this is already in the application object and probably doesn't have to be changed in Storage. Or are you thinking of another property?

**Comment by SandGrainOne** [comment]
@nkylstad It boils down to what we want the value to mean in practice. There was an assumption that the created date would mean deployment time. If that is still the desired meaning, altinn-studio would need to manage the value and treat it differently between first deploy and consecutive deploys.

**Comment by nkylstad** [comment]
Ah I see. Well, I have no strong preferences on whether Studio should control this or Storage. If you would like Studio to set the date as part of the application-object we pass to the Post endpoint then that's fine by me! We'll create an issue and try to find some time for it.

**Comment by olebhansen** [comment]
Refactor to use the existing "created" and "updated", as the dates should not be tampered with.

**Comment by acn-sbuad** [comment]
- Verified that created date is not unchanged in AT22. 
- Created by is not exposed in the API despite being defined in applicationmetadata.json in the app. 
- validFrom is also changed on redeploy, should this also be unchanged on redeploy ? 
-

**Comment by SandGrainOne** [comment]
Pretty sure CreatedBy would be visible on the API if it had a value. "Do not serialize empty/null fields".

**Comment by acn-sbuad** [comment]
[The app I have tested with does have the value set.](https://altinn.studio/repos/ttd/storage-end-to-end/src/branch/master/App/config/applicationmetadata.json#L79)

**Comment by SandGrainOne** [comment]
It could be that the GetUserId() method always return null when the request is being done by altinn.studio.

**Comment by acn-sbuad** [comment]
Question is why we are overwriting these values. The entity deploying the app might not be the same as the one that created/developed the app. And as mentioned altinn studio credentials are used towards storage. Why are we overwriting these values that are set by Altinn studio and define entities that live within the Altinn Studio scope i..e Altinn Studio user names?

**Comment by SandGrainOne** [comment]
No requirements creates confusing implementations. This is 5-6 year old code by bow.

**Comment by acn-sbuad** [comment]
True.. FYI @Ahmed-Ghanam might want to pause and agree on the requirements for future behavior before looking at a fix here

**Comment by SandGrainOne** [comment]
I think we can complete and close this issue as originally scoped only to the Created date. Then create a new issue for clarification about other properties. It should be discussed with the altinn-studio teams how to progress.

The `CreatedBy` and `LastChangedBy` properties can also be affected by the introduction to system users.

**Comment by Ahmed-Ghanam** [comment]
None of JSON objects returned by the [endpoint](https://[platform.at22.altinn.cloud/storage/api/v1/applications](https://platform.at22.altinn.cloud/storage/api/v1/applications)) has a createdby/createdBy attribute.

I agree with @SandGrainOne that we can close this issue as it keeps the created date unchanged. Can you confirm @acn-sbuad
