### ISSUE TITLE
Kall mot GET /storage/api/v1/instances?org=dmf&size=50  og header X-Ai-InstanceOwnerIdentifier filtrerer ikke resultatet

### ISSUE THREAD

**Issue by prange** [Altinn/altinn-storage#396]
### Description of the bug

jeg forsøker å hente ut alle instanser for en part basert på org nr:
GET /storage/api/v1/instances?org=dmf&size=50

X-Ai-InstanceOwnerIdentifier: ***
Der jeg har forsøkt å erstatte *** med "<orgnr>" , og "Organisation:<orgnr>".

Jeg får alltid alle skjema fra _alle_ parter, men forventer å bare å få instanser fra _gitt org_. 

I dokumentasjonen står det beskrevet at med gitt header skal svaret være filtrert.
<img width="1083" alt="Screenshot 2024-05-03 at 10 14 25" src="https://github.com/Altinn/altinn-storage/assets/355966/603eb851-1db7-4044-9a61-6aee623515e1">

Workaround er å laste ned alle instanser for alle apper, og så filtrere på klientsiden.

### Steps To Reproduce

Gjør et kall:
GET /storage/api/v1/instances?org=dmf

X-Ai-InstanceOwnerIdentifier: <orgnr>

**Comment by SandGrainOne** [comment]
Results of testing. Happy path is working as expected. Invalid input gives unwanted behavior. See #399
