### ISSUE TITLE
Extend free text search to find matched in blob content

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-storage#4]
Free text search in the message box should also present instances where the is a match in the blob data.

## Considerations
> Describe input (beyond tasks) on how the user story should be solved can be put here.

## Acceptance criteria
> Describe criteria here (i.e. What is allowed/not allowed (negative tesing), validations, error messages and warnings etc.)

## Specification tasks

- [ ] Development tasks are defined
- [ ] Test design / decide test need

## Development tasks
> Add tasks here

## Definition of done
Verify that this issue meets [DoD](https://confluence.brreg.no/display/T3KP/Definition+of+Done#DefinitionofDone-DoD%E2%80%93utvikling) (Only for project members) before closing.

- [ ] Documentation is updated (if relevant)
  - [ ] Technical documentation (docs.altinn.studio)
  - [ ] User documentation (altinn.github.io/docs)
- [ ] QA
- [ ] Manual test is complete (if relevant)
- [ ] Automated test is implemented (if relevant)
- [ ] All tasks in this userstory are closed (i.e. remaining tasks are moved to other user stories or marked obsolete)

**Comment by SandGrainOne** [comment]
This is out of scope for what Storage can deliver of search functionality. If this is something we need, the issue should be handled by a dedicated search micro service.
