### ISSUE TITLE
Investigate why local culture overrides the specified date-time format given in ToString(format)

### ISSUE THREAD

**Issue by olebhansen** [Altinn/altinn-storage#502]
@SandGrainOne found that testing locally, the application behaves differnetly (crashes) locally va. testing in a "proper" environment. The code tested sets an explicit dataformat that seems to be ignored (.ToString("yyyy-mm-dd HH:mm:ss"), that yielded the string "2024-09-24 12.35.44" - note the expected : timestamp delimitor vs. the actual produced .)

Code seems fragile (i.e. not conforming to the supplied format) and may cause unexpecded failures if not running in a place where the locale has a specific setting.

### Acceptance criteria: 
- [ ] Parsing of dates are not depending having a specific locale-settings at the OS level

**Comment by hansdragnes** [comment]
01OCT: Consider alternative method for serialization. Also, code working well as is hence not critical.

**Comment by hggutvik** [comment]
I found some proposed solutions on [this StackOverflow thread](https://stackoverflow.com/questions/24661362/formatting-datetime-ignore-culture) - might be worth a shot
![Image](https://github.com/user-attachments/assets/f881d80a-a273-400a-9cf6-161018e9972d)

**Comment by SandGrainOne** [comment]
Did a little bit of regression testing through advanced search in AT23. I'm finding no issue with the change.
