### ISSUE TITLE
DataElements without existing blobs can occur on error

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-storage#59]
### Description of the bug

Based on the flow in DataController we can risk a data element being left in cosmosDB although the blob has been deleted. 
There is no error handling to restore a datablob if deletion of the dataElement fails. 

We have an instance from SKD. DataGuid: 3275ea8a-06e8-4097-b410-5912463ffd18 where the blob is deleted, but the metadata still exists in CosmosDB. No exceptions found in logs for this particular blob, so this being the cause is not certain	

### Steps To Reproduce

Start storage component
Disconnect cosmosDB (so only blob storage is available to the storage component)
Send request to delete dataElement. 
See error

### Additional Information

The Blob Storage SDK is assumed to be able to restore a deleted Blob by using a snapshot. Investigate this.

**Comment by olebhansen** [comment]
Closing. All code related to this has been changed/re-written since this issue was created.
