### ISSUE TITLE
Extend advanced search to support search on status

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-storage#6]
## Description
Currently we only support "search in": inbox, archive and trash. 
But there are also other statuses we can filter searches on. 
We should look into supporting these 

## Screenshots

![image](https://user-images.githubusercontent.com/47737608/105331740-16e17200-5bd4-11eb-8667-33fd836cd7e8.png)

- Exclude "Venter på andre" (Current user not authorized to perform task.) Must be a separate issue.
    - Could potentially use altinn task type: feedback
- Exclude "Til signering". Signing is currently not a process step.

## Acceptance criteria
TBD

## Specification tasks

- [ ] Development tasks are defined
- [ ] Test design / decide test need

## Development tasks
- [ ] Documentation 
- [ ] QA
- [ ] Manual test
- [ ] Automated tes

**Comment by SandGrainOne** [comment]
Not planned for now.
