### ISSUE TITLE
Implement handling of large continuation in Cosmos tokens using Redis Cache 

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-storage#7]
## Description
When the GetInstances continuation token is too long and request returns 414 Request URI Too Long
A quick fix of limiting the size of the token to 7 kb has been implemented. 
This is not a long term fix, as the continuation token will increase in size as the amout of data in cosmos increased. 

Solution is to store the large continuation tokens somewhere else and use a guid that the end user can include in the request. 

Prerequisites: we have a RedisCache or some cache shared between all storage pods.
If continuation token returned from CosmosDB >= 7kB
cache the value and use a guid as the continuation token instead.
When a continuation token is sent to the controller.. if the format is guid, get the actual token from the cache and send on to cosmosDB.

## Considerations
> Would it be possible to add the continuation token in the header instead? 
Would we then be allowed to use the large cont.token ? 

## Acceptance criteria
- Large continuation tokens are stored in redis cache
- No continuation tokens are compressed

## Development tasks
- [ ] Remove ResponseContinuationTokenLimitInKb  in InstanceRepository
- [ ] Set up cache for continuation tokens
- [ ] Implement logic i InstancesController for handling large cont tokens.
[ ] Documentation is updated 
- [ ] QA
- [ ] Manual test is complete (if relevant)
- [ ] Automated test is implemented (if relevant)

## Test
> Add test cases here as checkboxes that are being tested as part of the changes.

**Comment by SandGrainOne** [comment]
Refinement 13.12.2022. We've tried to find cases where GetInstances has failed because of the continuation token without success. Performance for this endpoint also seems to be acceptable at the moment.

There are other issues related to GetInstances we would like to fix first.
