### ISSUE TITLE
ProcessHistoryItem.Occurred is populated with created date from InstanceEvent

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-storage#89]
### Description of the bug

During the mapping from instance events to `ProcessHistoryItem`, we use the `InstanceEvent` created date when populating the occured field. This will never be the same timestamp as the timestamps under the `ProcessInfo` property.

We need to look at the mapping to ensure we've picked the correct timestamp for each process history item.

### Steps To Reproduce

It's possible to reproduce the bug, but every single instance ever created can already be used to exemplify the issue.

### Additional Information

The issue was identified by brreg developers:
https://altinn.slack.com/archives/C02ESDSGPN1/p1667212783346829

### Suggested fix
We'll retrvive time stamp from ProcessInfo.Started and ProcessInfo.Ended for the two events respectively.

https://github.com/Altinn/altinn-storage/blob/main/src/Storage/Helpers/ProcessHelper.cs#L32

## Expected behaviour
The process history item occured property has the time stamp from the process event and not the instance event created property.

**Comment by acn-sbuad** [comment]
Verified in AT
